// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/jacadi-image-presentation/CurrentProductCard.tsx": () => import("../components/mockups/jacadi-image-presentation/CurrentProductCard.tsx"),
  "./components/mockups/jacadi-image-presentation/CurrentProductGallery.tsx": () => import("../components/mockups/jacadi-image-presentation/CurrentProductGallery.tsx"),
  "./components/mockups/jacadi-image-presentation/RefinedProductCard.tsx": () => import("../components/mockups/jacadi-image-presentation/RefinedProductCard.tsx"),
  "./components/mockups/jacadi-image-presentation/RefinedProductGallery.tsx": () => import("../components/mockups/jacadi-image-presentation/RefinedProductGallery.tsx"),
  "./components/mockups/jacadi-image-presentation/shared.tsx": () => import("../components/mockups/jacadi-image-presentation/shared.tsx")
};
